export const SHOW_TICKET = 'SHOW_TICKET';
export const CLOSE_TICKET = 'CLOSE_TICKET';
export const CREATE_TICKET = 'CREATE_TICKET';
export const RESOLVED_CREATE_TICKET = 'RESOLVED_CREATE_TICKET';
export const UPDATE_TICKET = 'UPDATE_TICKET';
export const RESOLVED_UPDATE_TICKET = 'RESOLVED_UPDATE_TICKET';
export const DELETE_TICKET = 'DELETE_TICKET';
export const RESOLVED_DELETE_TICKET = 'RESOLVED_DELETE_TICKET';
export const EDIT_TICKET = 'EDIT_TICKET';
export const SHOW_CREATE_FORM = 'SHOW_CREATE_FORM';
export const CLOSE_CREATE_FORM = 'CLOSE_CREATE_FORM';
export const ADD_TICKET_FROM_SOCKETS = 'ADD_TICKET_FROM_SOCKETS';

